CREATE SEQUENCE seq_customer_id
START WITH 1
INCREMENT BY 1;


CREATE SEQUENCE seq_employee_id
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_account_id
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_card_id
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_beneficiary_id
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_transaction_id
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_loan_id
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_loan_pay_id
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_audit_log_id
START WITH 1
INCREMENT BY 1; 